### ISSUE TITLE
Latest update breaks icons

### ISSUE THREAD

**Issue by TheKamboy** [JordanSantiagoYT/FNF-JS-Engine#1105]
### Describe your bug here.

Using the latest patch update, icons are being cut off. Not sure why.

>[!NOTE]
> 1.48.1 isn't in the version list for the question below...

### What version did the bug occur?

1.48.0

### Did you check if the problem occurs in the latest build?

Yes

### Commit build or Release build?

Release build

### Did you check if this issue is already known?

Yes

### Did you check for any similar issues?

Yes

### Command Prompt/Terminal/Crash logs (if existing)

I don't got logs, but I do have screenshots!

# Latest Patch (v1.48.1)

![Image](https://github.com/user-attachments/assets/d6a1ab81-731b-432e-8ec5-f57fca1ae3cc)

# The version before (v1.48.0)

![Image](https://github.com/user-attachments/assets/4e0523d5-41fb-429b-a762-321a3e19e39a)

### Have you identified any steps to reproduce the bug?

Just open freeplay and check the icons.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

nah

**Comment by moxie-coder** [comment]
if it has an win icon you’d have to specify that in an json file `hasWinIcon` for it, I did that to try to fix some issues

**Comment by moxie-coder** [comment]
actually sorry I mean set that to false since it’s true by default but that was probably an bad idea

**Comment by TheKamboy** [comment]
> actually sorry I mean set that to false since it’s true by default but that was probably an bad idea

its fine

**Comment by TheStinkern** [comment]
is it fixed though

**Comment by TheKamboy** [comment]
should i test the latest action build?

**Comment by TheStinkern** [comment]
Yes

**Comment by nate902011** [comment]
I found out this issue only happens to big icons, and I have a workaround; open your icon in an image software and increase your canvas size to as if it had a winning icon (dimensions: 1.5x by 1.0y, anchor image to the left). Then copy and paste your neutral icon to the rightmost side of your image. Then save. Here's what my fixed icons look like compared to my unfixed ones:
Fixed:
![Image](https://github.com/user-attachments/assets/3d9d16cd-e86e-4b13-a812-bdb2e6588a3e)
Unfixed:
![Image](https://github.com/user-attachments/assets/dc99121b-4d13-4036-b0c3-018f312e6f77)

**Comment by TheStinkern** [comment]
Did you check on the latest build, @nate902011

**Comment by nate902011** [comment]
> Did you check on the latest build, [@nate902011](https://github.com/nate902011)

I did on the latest release build since that's what I'm using at the moment. I will check on the latest action build.

**Comment by nate902011** [comment]
I just tried using the latest action build and the icon bug is still present. I'll just use my workaround.

**Comment by moxie-coder** [comment]
> I just tried using the latest action build and the icon bug is still present. I'll just use my workaround.

sorry it’s hard to account for literally every icon resolution, I’ll try looking at it a little further

**Comment by nate902011** [comment]
> > I just tried using the latest action build and the icon bug is still present. I'll just use my workaround.
> 
> sorry it’s hard to account for literally every icon resolution, I’ll try looking at it a little further

Ok

**Comment by moxie-coder** [comment]
try the latest nightly build @TheKamboy @nate902011

**Comment by nate902011** [comment]
Now, there's 2 issues with this build that i notice off the bat. 1. (i forgot to mention this in the last time i responded but) now key presses in the main menu state and settings state result in double hits (so it thinks i hit any direction twice) and 2. icons don't show up anymore. Here's some footage of a reenactment of me booting it up and going into freeplay:
https://drive.google.com/file/d/1A8BUitMr609Da9KG4w06JghDCv4Rkbs2/view?usp=sharing

sorry for responding a little late

also pls don't mind my mod, it shouldn't do anything to affect my demonstration since it's softmodded.

**Comment by TheKamboy** [comment]
Sorry for not talking a lot. I'm going to compile the latest commit and test.

**Comment by TheKamboy** [comment]
It might be a bit before I can though.

**Comment by nate902011** [comment]
> Sorry for not talking a lot. I'm going to compile the latest commit and test.

they put up a nightly prerelease in releases to test. that's where i got my footage from

**Comment by TheKamboy** [comment]
> > Sorry for not talking a lot. I'm going to compile the latest commit and test.
> 
> they put up a nightly prerelease in releases to test. that's where i got my footage from

GLIB error, so I will have to compile it.

**Comment by TheKamboy** [comment]
got this error when trying to compile

<img width="886" height="119" alt="Image" src="https://github.com/user-attachments/assets/c8e652b7-8d26-4f50-919b-919e399593d9" />

**Comment by moxie-coder** [comment]
> > > Sorry for not talking a lot. I'm going to compile the latest commit and test.
> > 
> > 
> > they put up a nightly prerelease in releases to test. that's where i got my footage from
> 
> GLIB error, so I will have to compile it.

Try downloading from here then? https://github.com/JordanSantiagoYT/FNF-JS-Engine/actions/runs/16016646834

**Comment by moxie-coder** [comment]
actually nevermind that, try using flixel-ui 2.6.0, I just looked at the changelog for 2.6.1 and oops lol

**Comment by TheKamboy** [comment]
> actually nevermind that, try using flixel-ui 2.6.0, I just looked at the changelog for 2.6.1 and oops lol

alright, ill try that

**Comment by TheKamboy** [comment]
had to update the project file too, but its compiling now

**Comment by TheKamboy** [comment]
alright the compiled version is broken (theres too many logs too send i think)
ill try the actions build

**Comment by TheKamboy** [comment]
actions build complains about glib, ima just use `wine` and test the windows build

**Comment by TheKamboy** [comment]
you guys gotta be trolling me, wtf is this?????

<img width="1015" height="620" alt="Image" src="https://github.com/user-attachments/assets/4133ce7b-f3cd-424f-b62b-def63a87a195" />

this is funny

**Comment by moxie-coder** [comment]
> actions build complains about glib, ima just use `wine` and test the windows build

are you using Debian/Ubuntu based Linux? If so try doing this `sudo apt-get install libglib2.0-dev` then trying again

**Comment by moxie-coder** [comment]
actually nevermind because I was able to reproduce on my end, I honestly don't even know how tf this happened. Because they were literally working before

**Comment by moxie-coder** [comment]
I've fixed the missing icons in https://github.com/JordanSantiagoYT/FNF-JS-Engine/commit/86f2ec93f177baaa54ac4d30411e7600fc7010f9 but I don't know if I fixed the 600x150 icons because I haven't gotten to that shit yet.

**Comment by moxie-coder** [comment]
some new developments, I've gotten the *idle* to finally work, but not when losing. But I might have an hunch as to why
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/bb73b43e-3d60-47a5-93fe-a91e9f0f2841" />
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/be0796ab-ae56-4812-b1f9-f3b86f3b78db" />

**Comment by TheKamboy** [comment]
> > actions build complains about glib, ima just use `wine` and test the windows build
> 
> are you using Debian/Ubuntu based Linux? If so try doing this `sudo apt-get install libglib2.0-dev` then trying again

Yeah, I recently switched to Zorin OS after purchasing the Pro version. I'll give that a shot.

**Comment by moxie-coder** [comment]
I’ve given up in adding 600x150 icon support because it’s way too much effort for me and a lot of math I just don’t know

**Comment by TheKamboy** [comment]
Alright, btw that doesn't seem to work. It might work when Zorin updates to a newer LTS.

**Comment by moxie-coder** [comment]
should be resolved in https://github.com/JordanSantiagoYT/FNF-JS-Engine/commit/f07b3e92830cce9fc60c9d1cefa4981b469cf686

**Comment by nate902011** [comment]
The opponent icons are now fine but the BF icons are split in half:

<img width="927" height="204" alt="Image" src="https://github.com/user-attachments/assets/ac16d173-854b-463d-8991-d9ef84c6d60c" />

And the main menu and setting double hit bug is still in the game from the last nightly build.

**Comment by moxie-coder** [comment]
> The opponent icons are now fine but the BF icons are split in half:
> 
> <img alt="Image" width="927" height="204" src="https://private-user-images.githubusercontent.com/134645371/465647869-ac16d173-854b-463d-8991-d9ef84c6d60c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTIzNDE2NjIsIm5iZiI6MTc1MjM0MTM2MiwicGF0aCI6Ii8xMzQ2NDUzNzEvNDY1NjQ3ODY5LWFjMTZkMTczLTg1NGItNDYzZC04OTkxLWQ5ZWY4NGM2ZDYwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcxMlQxNzI5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2JhZmRmYzE1ZGI0ODE1Mzc2ZTQ3MGNmMjIwMTUzYmM3ZTUxODU1ZWRkMjk4YmI2ODRmNWExMzA4YmU2OThkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DE-Gsspxj2bE1YTVZMLjft9R0SfumAyO_6gJ8KN8w2I">
> And the main menu and setting double hit bug is still in the game from the last nightly build.

well, I’ve tried honestly.

Also I don’t know about that issue, that should probably be made as an separate issue

**Comment by nate902011** [comment]
> > The opponent icons are now fine but the BF icons are split in half:
> > <img alt="Image" width="927" height="204" src="https://private-user-images.githubusercontent.com/134645371/465647869-ac16d173-854b-463d-8991-d9ef84c6d60c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTIzNDE2NjIsIm5iZiI6MTc1MjM0MTM2MiwicGF0aCI6Ii8xMzQ2NDUzNzEvNDY1NjQ3ODY5LWFjMTZkMTczLTg1NGItNDYzZC04OTkxLWQ5ZWY4NGM2ZDYwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcxMlQxNzI5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2JhZmRmYzE1ZGI0ODE1Mzc2ZTQ3MGNmMjIwMTUzYmM3ZTUxODU1ZWRkMjk4YmI2ODRmNWExMzA4YmU2OThkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DE-Gsspxj2bE1YTVZMLjft9R0SfumAyO_6gJ8KN8w2I">
> > And the main menu and setting double hit bug is still in the game from the last nightly build.
> 
> well, I’ve tried honestly.
> 
> Also I don’t know about that issue, that should probably be made as an separate issue

Alright

**Comment by TheKamboy** [comment]
> The opponent icons are now fine but the BF icons are split in half:
> 
> <img width="927" height="204" alt="Image" src="https://github.com/user-attachments/assets/ac16d173-854b-463d-8991-d9ef84c6d60c" />
> 
> And the main menu and setting double hit bug is still in the game from the last nightly build.

Bambi ate his face lol
